package org.qainsights.jmeter.ai.generate;

import java.util.Map;

/**
 * Serializes a {@link TestPlanModel} to a JMeter {@code .jmx} document:
 * Test Plan → Thread Group → one {@code HTTPSamplerProxy} (with a
 * {@code HeaderManager}) per request. Output opens directly in the JMeter GUI.
 */
public final class JmxTestPlanWriter {

    private static final String JMETER_VERSION = "5.6.3";

    private JmxTestPlanWriter() {
    }

    public static String write(TestPlanModel model) {
        StringBuilder sb = new StringBuilder(1024);
        sb.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
        sb.append("<jmeterTestPlan version=\"1.2\" properties=\"5.0\" jmeter=\"").append(JMETER_VERSION).append("\">\n");
        sb.append("  <hashTree>\n");
        appendTestPlan(sb, model.getName());
        sb.append("    <hashTree>\n");
        appendThreadGroup(sb);
        sb.append("      <hashTree>\n");
        for (HttpRequestSpec req : model.getRequests()) {
            appendSampler(sb, req);
        }
        sb.append("      </hashTree>\n");
        sb.append("    </hashTree>\n");
        sb.append("  </hashTree>\n");
        sb.append("</jmeterTestPlan>\n");
        return sb.toString();
    }

    private static void appendTestPlan(StringBuilder sb, String name) {
        sb.append("    <TestPlan guiclass=\"TestPlanGui\" testclass=\"TestPlan\" testname=\"")
          .append(attr(name)).append("\" enabled=\"true\">\n");
        sb.append("      <boolProp name=\"TestPlan.functional_mode\">false</boolProp>\n");
        sb.append("      <boolProp name=\"TestPlan.serialize_threadgroups\">false</boolProp>\n");
        sb.append("      <elementProp name=\"TestPlan.user_defined_variables\" elementType=\"Arguments\" "
                + "guiclass=\"ArgumentsPanel\" testclass=\"Arguments\" testname=\"User Defined Variables\" enabled=\"true\">\n");
        sb.append("        <collectionProp name=\"Arguments.arguments\"/>\n");
        sb.append("      </elementProp>\n");
        sb.append("      <stringProp name=\"TestPlan.comments\">Generated by FeatherWand from an API spec / HAR capture.</stringProp>\n");
        sb.append("      <stringProp name=\"TestPlan.user_define_classpath\"></stringProp>\n");
        sb.append("    </TestPlan>\n");
    }

    private static void appendThreadGroup(StringBuilder sb) {
        sb.append("      <ThreadGroup guiclass=\"ThreadGroupGui\" testclass=\"ThreadGroup\" "
                + "testname=\"Thread Group\" enabled=\"true\">\n");
        sb.append("        <stringProp name=\"ThreadGroup.num_threads\">1</stringProp>\n");
        sb.append("        <stringProp name=\"ThreadGroup.ramp_time\">1</stringProp>\n");
        sb.append("        <boolProp name=\"ThreadGroup.same_user_on_next_iteration\">true</boolProp>\n");
        sb.append("        <stringProp name=\"ThreadGroup.on_sample_error\">continue</stringProp>\n");
        sb.append("        <elementProp name=\"ThreadGroup.main_controller\" elementType=\"LoopController\" "
                + "guiclass=\"LoopControlPanel\" testclass=\"LoopController\" testname=\"Loop Controller\" enabled=\"true\">\n");
        sb.append("          <stringProp name=\"LoopController.loops\">1</stringProp>\n");
        sb.append("          <boolProp name=\"LoopController.continue_forever\">false</boolProp>\n");
        sb.append("        </elementProp>\n");
        sb.append("        <stringProp name=\"ThreadGroup.delay\"></stringProp>\n");
        sb.append("      </ThreadGroup>\n");
    }

    private static void appendSampler(StringBuilder sb, HttpRequestSpec req) {
        sb.append("        <HTTPSamplerProxy guiclass=\"HttpTestSampleGui\" testclass=\"HTTPSamplerProxy\" testname=\"")
          .append(attr(req.getName())).append("\" enabled=\"true\">\n");
        appendArguments(sb, req);
        sb.append("          <stringProp name=\"HTTPSampler.domain\">").append(text(req.getDomain())).append("</stringProp>\n");
        sb.append("          <stringProp name=\"HTTPSampler.port\">").append(req.getPort() > 0 ? req.getPort() : "").append("</stringProp>\n");
        sb.append("          <stringProp name=\"HTTPSampler.protocol\">").append(text(req.getProtocol())).append("</stringProp>\n");
        sb.append("          <stringProp name=\"HTTPSampler.path\">").append(text(req.getPath())).append("</stringProp>\n");
        sb.append("          <stringProp name=\"HTTPSampler.method\">").append(text(req.getMethod())).append("</stringProp>\n");
        sb.append("          <boolProp name=\"HTTPSampler.follow_redirects\">true</boolProp>\n");
        sb.append("          <boolProp name=\"HTTPSampler.use_keepalive\">true</boolProp>\n");
        if (req.hasBody()) {
            sb.append("          <boolProp name=\"HTTPSampler.postBodyRaw\">true</boolProp>\n");
        }
        sb.append("          <stringProp name=\"HTTPSampler.contentEncoding\"></stringProp>\n");
        sb.append("        </HTTPSamplerProxy>\n");
        sb.append("        <hashTree>\n");
        appendHeaderManager(sb, req);
        sb.append("        </hashTree>\n");
    }

    private static void appendArguments(StringBuilder sb, HttpRequestSpec req) {
        sb.append("          <elementProp name=\"HTTPsampler.Arguments\" elementType=\"Arguments\" "
                + "guiclass=\"HTTPArgumentsPanel\" testclass=\"Arguments\" testname=\"User Defined Variables\" enabled=\"true\">\n");
        if (req.hasBody()) {
            sb.append("            <collectionProp name=\"Arguments.arguments\">\n");
            sb.append("              <elementProp name=\"\" elementType=\"HTTPArgument\">\n");
            sb.append("                <boolProp name=\"HTTPArgument.always_encode\">false</boolProp>\n");
            sb.append("                <stringProp name=\"Argument.value\">").append(text(req.getBody())).append("</stringProp>\n");
            sb.append("                <stringProp name=\"Argument.metadata\">=</stringProp>\n");
            sb.append("              </elementProp>\n");
            sb.append("            </collectionProp>\n");
        } else {
            sb.append("            <collectionProp name=\"Arguments.arguments\"/>\n");
        }
        sb.append("          </elementProp>\n");
    }

    private static void appendHeaderManager(StringBuilder sb, HttpRequestSpec req) {
        if (req.getHeaders().isEmpty()) {
            return;
        }
        sb.append("          <HeaderManager guiclass=\"HeaderPanel\" testclass=\"HeaderManager\" "
                + "testname=\"HTTP Header Manager\" enabled=\"true\">\n");
        sb.append("            <collectionProp name=\"HeaderManager.headers\">\n");
        for (Map.Entry<String, String> h : req.getHeaders().entrySet()) {
            sb.append("              <elementProp name=\"\" elementType=\"Header\">\n");
            sb.append("                <stringProp name=\"Header.name\">").append(text(h.getKey())).append("</stringProp>\n");
            sb.append("                <stringProp name=\"Header.value\">").append(text(h.getValue())).append("</stringProp>\n");
            sb.append("              </elementProp>\n");
        }
        sb.append("            </collectionProp>\n");
        sb.append("          </HeaderManager>\n");
        sb.append("          <hashTree/>\n");
    }

    /** XML element-text escaping. */
    static String text(String s) {
        if (s == null) {
            return "";
        }
        StringBuilder sb = new StringBuilder(s.length() + 8);
        for (int i = 0; i < s.length(); i++) {
            char c = s.charAt(i);
            switch (c) {
                case '&': sb.append("&amp;"); break;
                case '<': sb.append("&lt;"); break;
                case '>': sb.append("&gt;"); break;
                default: sb.append(c);
            }
        }
        return sb.toString();
    }

    /** XML attribute escaping (adds quote handling). */
    static String attr(String s) {
        return text(s).replace("\"", "&quot;");
    }
}
